version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: golves-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golves
      MYSQL_USER: golves
      MYSQL_PASSWORD: golves
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis 缓存
  redis:
    image: redis:alpine
    container_name: golves-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: 